# Generated by Django 5.0.6 on 2024-07-19 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reviews", "0002_rename_content_review_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="post",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Critique",
                to="reviews.post",
            ),
        ),
    ]
