# Generated by Django 5.0.6 on 2024-07-26 13:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reviews", "0004_alter_review_post"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo",
            name="image",
            field=models.ImageField(default="static/no-image.png", upload_to=""),
        ),
    ]
