# Generated by Django 5.0.6 on 2024-07-26 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reviews", "0005_alter_photo_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo",
            name="image",
            field=models.ImageField(upload_to=""),
        ),
        migrations.AlterField(
            model_name="review",
            name="photo",
            field=models.ForeignKey(
                blank=True,
                default="static/no-image.png",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="reviews.photo",
            ),
        ),
    ]
