# Generated by Django 5.0.6 on 2024-08-15 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0011_userfollows'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfollows',
            name='blocked',
        ),
    ]
