# Generated by Django 5.0.6 on 2024-08-15 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0012_remove_userfollows_blocked'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserFollows',
        ),
    ]
