# Generated by Django 5.0.6 on 2024-08-27 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reviews", "0015_remove_review_post_post_review"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="review",
        ),
        migrations.AddField(
            model_name="review",
            name="post",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="reviews.post",
            ),
        ),
    ]
