# Generated by Django 5.0.6 on 2024-07-25 12:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("authentication", "0003_alter_user_profile_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="groups",
            field=models.ManyToManyField(
                related_name="user_auth_groups", to="auth.group"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_permissions",
            field=models.ManyToManyField(
                related_name="user_auth_permissions", to="auth.permission"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                error_messages={"unique": "Ce nom d'utilisateur est déjà attribué"},
                max_length=50,
                unique=True,
                verbose_name="username",
            ),
        ),
    ]
