# Generated by Django 5.0.6 on 2024-08-06 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_user_follow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(default='static/default_profile.png', upload_to='profile_photos/', verbose_name='photo de profil'),
        ),
    ]
