# Generated by Django 5.0.6 on 2024-08-15 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_user_profile_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='follow',
            new_name='follows',
        ),
    ]
